name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify -f mega-app/pom.xml
      - name: Move artifact to staging
        run: mkdir staging && cp mega-app/target/*.jar staging
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
